<?

/**
 * Implements hook_block_info().
 * @return array
 */
function airtime_block_block_info()
{
	$blocks = array(
		'airtime_block' => array(
			'info' => t('Airtime'),
			'cache' => DRUPAL_NO_CACHE
		)
	);

	return $blocks;
}

/**
 *  Implements hook_block_view().
 */
function airtime_block_block_view($delta = '')
{
	$block = array();
	if($delta == 'airtime_block')
	{
		if(airtime_api_config_check())
		{
			$block['subject'] = t('Airtime');
			$block['content'] = airtime_block_contents();
		}
	}

	return $block;
}

/**
 * Implements hook_theme().
 * @return mixed
 */
function airtime_block_theme()
{
	$theme['airtime_block'] = array(
		'variables' => array(
			'current_track' => null
		),
		'template' => 'theme/airtime_block--block'
	);
	return $theme;
}

function airtime_block_contents()
{
	$options = airtime_api_config();
	$airtime = new Airtime($options);
	$live = $airtime->api('live-info');

	$output = array();

	if($live)
	{
		if(!empty($live->current->name))
		{
			$output['current_track']= $live->current->name;
		}

		if(!empty($live->currentShow[0]->name))
		{
			$output['current_show'] = $live->currentShow[0]->name;
		}

		$output['station_link'] = l(t('Link to station'), $airtime->getHost(), array(
			'attributes' => array(
				'target' => '_blank'
			))
		);

	}

	return theme('airtime_block', $output);
}