<?

/**
 * @return array
 * Implements hook_menu
 */
function airtime_api_menu()
	{
		$items = array();

		$items['airtime/api'] = array(
			'type' => MENU_CALLBACK,
			'page callback' => 'airtime_api_handler',
			'access callback' => 'user_access',
    		'access arguments' => array('access content')
		);

		return $items;
	}

function airtime_api_handler()
	{
		if(arg(2) != '')
			{
				$method = htmlspecialchars(arg(2));
				$options = array(
					'host' => 'http://airtime-demo.sourcefabric.org',
					'api_key' => null
				);
				$airtime = new Airtime($options);
				if(is_numeric(arg(3)))
				{
					$arg = arg(3);
					drupal_json_output($airtime->get($method, $arg));
				}
				drupal_json_output($airtime->get($method));
			}
	}

